7.x tableselect delta release
Islandora/islandora_solr_metadata pull request #57
Opened 2017-03-24 17:31 UTC by MorganDawe

**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-1952)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
Additional related JIRA ticket: [ISLANDORA-1903](https://jira.duraspace.org/browse/ISLANDORA-1903)
# What does this Pull Request do?
When adding more than 20 rows to an islandora solr metadata configuration, the table select will stop maintaining weights, preventing users from saving an adjusted fields weight . This appears to relate to [a previous JIRA ticket](https://jira.duraspace.org/browse/ISLANDORA-1903) that allowed row weights to be shown. This ticket implements the row delta to allow these modifications to be saved.

# What's new?
Row weights are now preservable on the tableselect in the islandora_solr_metadata configuration page.

# How should this be tested?
* include this pull request in local code 
* Create an islandora_solr_metadata configuration
* Add 20 ~ 30 fields to the metadata config.
* Try to adjust the last two fields, and save. This should result in erratic behaviour, and the field weights not being saved as desired.

# Interested parties
Tag @Islandora/7-x-1-x-committers

2017-03-27 14:38 UTC, DiegoPino commented
@MorganDawe is this a bugfix that should go into our release since I see a pull request against 7.x-1.9? We should discuss this during this week's call to make sure it will be able to do so since only blockers are a must (which does not mean a minor fix can go into the process, just not priority). Thanks!

2017-03-27 14:44 UTC, DiegoPino commented
@MorganDawe update and sorry 😄 
All fine, I just saw the other pull request #56. It is named differently and none of the pull requests are linked to the Jira ticket via branch naming and the Jira ticket did not have a fix version so got all confused.
Ok, this is fine: it is a bug fix with 2x pull requests. Will add some time during this week's call to discuss it. Thanks again.

2017-04-07 13:38 UTC, DiegoPino requested changes
Remove travis commit that got mixed while rebasing?

2017-04-07 13:38 UTC, DiegoPino commented on .travis.yml
> +before_script:
Would prefer if you removed this full chunk. This is not part of this ticket and seems more like an issue with the rebase.

2017-04-07 13:43 UTC, MorganDawe commented
Removed travis goof's. Thank's @DiegoPino.

2017-04-07 13:44 UTC, DiegoPino commented
@MorganDawe still some issues. Just a suggestion: start from a fresh 7.x-1.9 branch, create a new one based on that nammed `7.x-tableselect-delta-release`apply your changes manually (there are, thank god just, a few) , commit, and then force push that branch to your fork. The new set removed even some pieces of Travis and our release version in the info file.

2017-04-07 14:05 UTC, MorganDawe commented
Updated pull

2017-04-07 14:31 UTC, DiegoPino approved these changes

2017-04-10 18:54 UTC, merged

2017-04-10 18:57 UTC, DiegoPino commented
@MorganDawe @jordandukart both merged. Jira ticket closed.