Added option to expand or collapse details on metadata view
Islandora/islandora_solr_metadata pull request #66
Opened 2017-12-18 22:28 UTC by jyobb

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1252

# What does this Pull Request do?

Added a configuration option that allows users to select the default collapse state of the details metadata

# What's new?
Added a drupal variable to the config form.  Set this value as a template variable.  Check the variable in the template at display time.

# How should this be tested?

Enable and disable details view collapse and check that the behaviour was as expected.

# Additional Notes:
Hope I did this correctly

May want to change documentation to reflect this new option.

# Interested parties
@Islandora/7-x-1-x-committers

2017-12-19 15:58 UTC, DiegoPino requested changes
Hi @jyobb. You have a few Drupal Coding standard issues, see here https://travis-ci.org/Islandora/islandora_solr_metadata/jobs/318325673#L704-L713 Mostly spacing/identation

2018-05-26 15:37 UTC, bencomp commented
I haven't tested this, but if I understand the code correctly, changing the machine name of the metadata will leave the variable that contains the 'expand/collapse' state unchanged. I don't supposed many people will change the machine name of their metadata profiles often, but if you edit them this will leave unmanaged variables in the database.

2018-07-12 15:44 UTC, rosiel commented
This seems like a worthy addition to me. @jyobb if you can look at the remaining coding standards errors, 

sites/all/modules/islandora_solr_metadata/includes/config.inc:
 +225: [minor] No space before comment text; expected "// Add in truncation fields for description." but found "//Add in truncation fields for description."

sites/all/modules/islandora_solr_metadata/theme/theme.inc:
 +68: [minor] Inline comments must end in full-stops, exclamation marks, or question marks
 +68: [minor] Line exceeds 80 characters; contains 89 characters
 +69: [minor] Whitespace found at end of line

and a naming consideration: Since the variable is titled "Display fields expanded" and 1 (checked) results in the details expanded, could you rename:
* islandora_solr_metadata_collapse_{config_id} to islandora_solr_metadata_expand_{config_id}
* $collapse to $expand_metadata in 
* $collapse_default to $expand_default in theme.inc
* $variables['not_collapsed'] to $variables['expanded']

And add 'collapsible' even when not collapsed by default?

Also, all variables added by this module need to be removed in the install file's uninstall hook, and/or deleted when the configuration was deleted. (Alternately, another way to save this variable could be in the database table islandora_solr_metadata_associations, though that would require a schema update, it would probably be the technically better way to do this)

2025-03-05 18:36 UTC, DonRichards commented
## Tech call: 
closing because no activity.

2025-03-05 18:36 UTC, closed without merging